#### Script to join information about survey visits from visit_info.R 
#### to the presence/absence data generated by tabulate.R so that
#### each presence/absence record is attached to habitat, disturbance info etc

#### Then, both Solent survey datasets are joined together and the resultant
#### dataset is written to solent.csv

require(tidyr) # for spread()
require(dplyr) # for join() which is much faster than merge()
require(Hmisc) # capitalize
require(magrittr) # ceci %>% n'est pas un pipe


## convert bseen to wide form - need to drop unique row identifier 'spvis'
bwide <- spread(bseen[,names(bseen)!='spvis'], key = sp, value=count) 
bwide%<>%droplevels # remove an unused factor level
## convert cseen to wide form
cwide <- spread(cseen[,names(cseen)!='spvis'], key = sp, value=count)
## convser sseen to wide form
swide <- spread(sseen[,names(sseen)!='spvis'], key = sp, value=count)


## join bseen to birds_visitinfo
intersect(names(bwide), names(birds_visitinfo)) # check they have a column in common
bjoin <- left_join(bwide, birds_visitinfo)

## join cseen to clean_visitinfo
intersect(names(cwide), names(clean_visitinfo))
cjoin <- left_join(cwide, clean_visitinfo)

## join sseen to swbg_visitinfo
intersect(names(swide), names(swbg_visitinfo))
sjoin <- left_join(swide, swbg_visitinfo)

all.equal(names(bjoin), names(cjoin)) # visitid != Visit.ID
names(cjoin)[which(names(cjoin)=='visitid')] <- 'Visit.ID' # standardise visit ID name
names(sjoin)[which(names(sjoin)=='visitid')] <- 'Visit.ID' # standardise visit ID name
all.equal(names(bjoin), names(cjoin)) # now it's true!


#### combine 'birds' and 'clean' datasets
solent <- rbind(bjoin, cjoin, sjoin) # join both datasets together
# are all rows preserved?
nrow(bjoin)+nrow(cjoin)+nrow(sjoin)==nrow(solent) # yes :)

# check that data formatting is still ok
str(solent) # looks good - categories for e.g. habitat still need tidying
solent$Activity %<>% factor # convert from character to factor
summary(solent)






#### clean workspace ####
rm(bseen, bwide, cseen, cwide, birds_visitinfo, clean_visitinfo)
rm(sseen, swide, swbg_visitinfo, swbg, swbg_id, sjoin)
rm(birds, bjoin, cjoin, clean, cleanarableinfo, 
   birds_id, birds_splist, clean_id, clean_splist, negrecs)


## remove package so that extract() function from magrittr still works
## (it is masked by tidyr's own extract function!)
detach("package:tidyr", unload=TRUE)

#### write joined data to a CSV
#### note that this will overwrite the previous version without warning!
# write.csv(solent, file='Data/solent.csv', na="", row.names = F)

# write random subsample of data to CSV to test loading into QGIS
# write.csv( solent[sample(1:nrow(solent), 100, replace=F),] , 
#                   file='solent_test.csv', na="", row.names = F)